### ISSUE TITLE
Difficulty integrating new primitive_step in specialization

### ISSUE THREAD

**Issue by palibhasataolamang** [Bioprotocols/paml#104] opened 2022-02-01 09:22 UTC
I'm attempting to integrate logic for Transfer into a new specialization function for the Opentrons OT2. Unlike preimplemented provision_container(), my new function transfer_to() which is based on provision_container() executes twice, once with sampleArrays, and another with sampleMasks. In addition, its not executed in the correct order as declared in the main script. Maybe I screwed up somewhere?

[ot2Specialization.tar.gz](https://github.com/Bioprotocols/paml/files/7977197/ot2Specialization.tar.gz)

**Comment by jakebeal** [comment] 2022-02-01 11:24
Can you provide either a link to an executable version of your project or a trace of the execution? That will help for understanding how to reproduce your issue.

**Comment by palibhasataolamang** [comment] 2022-02-01 11:37
https://github.com/friendzymes/paml/

The file is paml/examples/OT2TestGen.py

**Comment by jakebeal** [comment] 2022-02-01 12:52
That is quite curious... I can reproduce the error, but haven't been able to trace the cause yet. I suspect it may have something to do with token propagation when there are multiple dynamic inputs. @danbryce : have you seen an issue like this before?

**Comment by palibhasataolamang** [comment] 2022-02-01 14:16
Just to add, I tried working around that problem by using String Literals for source and destination, but it still not properly ordered.

**Comment by danbryce** [comment] 2022-02-02 20:50
I think I found the bug.  The execution engine has a bug in how it determines which edges in the protocol use a node as the source.  Its using a python predicate of the form `a in b` where `a = https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/CallBehaviorAction1` and there are values for `b` of the form `b = https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/CallBehaviorAction11`.  I think the logic is meant to match against values of `b = https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/CallBehaviorAction1/InputPin1`.  @jakebeal is there an sbol way to check whether a URI is a prefix of, or equal to, another?

**Comment by rpgoldman** [comment] 2022-02-02 21:08
@danbryce Do you need something SBOL-specific?  The reason I ask is that if these are `rdflib` URIs, then they are also python strings and you can just use string comparisons (or `os.path` comparisons) to do what you want.

**Comment by danbryce** [comment] 2022-02-02 21:11
No nothing specific. Just want a clean way to handle URIs where prefix checks are handled as something other than substring checks. 

Dan

**Comment by jakebeal** [comment] 2022-02-02 21:11
@danbryce I'd recommend using `sbol_utilities.workarounds.get_parent` to peel back from a `Pin` to its parent.

(This implemented a pending pySBOL feature to get parent relations directly https://github.com/SynBioDex/pySBOL3/issues/234)

**Comment by danbryce** [comment] 2022-02-02 21:12
Thanks. That’s what I need. 

Dan

**Comment by danbryce** [comment] 2022-02-03 23:28
@palibhasataolamang I merged the fix in #108 and think its ready for you to pull into your fork.

**Comment by palibhasataolamang** [comment] 2022-02-04 04:01
> @palibhasataolamang I merged the fix in #108 and think its ready for you to pull into your fork.  

Updated. Confirmed it works. Thank you.

**Comment by danbryce** [comment] 2022-02-04 14:00
Awesome!

**Closed by danbryce** 2022-02-04 14:00 UTC
